# Generated by Django 6.0.2 on 2026-02-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('region', models.CharField(choices=[('MO', 'Мондштадт'), ('LY', 'Ли Юэ'), ('IN', 'Инадзума'), ('SU', 'Сумеру'), ('FO', 'Фонтейн'), ('NA', 'Натлан'), ('NK', 'Нод-Край'), ('SN', 'Снежная')], max_length=2, verbose_name='Регион')),
                ('element', models.CharField(choices=[('A', 'Анемо'), ('G', 'Гео'), ('E', 'Электро'), ('D', 'Дендро'), ('H', 'Гидро'), ('P', 'Пиро'), ('C', 'Крио')], max_length=1, verbose_name='Элемент')),
            ],
        ),
    ]
