# Generated by Django 6.0.2 on 2026-02-18 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('boss_name', models.CharField(max_length=200, verbose_name='Название босса')),
            ],
        ),
        migrations.AlterModelOptions(
            name='character',
            options={'verbose_name': 'Персонаж', 'verbose_name_plural': 'Персонажи'},
        ),
        migrations.AddField(
            model_name='character',
            name='weekly_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.weeklymaterial'),
        ),
    ]
