# Generated by Django 6.0.2 on 2026-02-19 06:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_weeklymaterial_alter_character_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklymaterial',
            options={'verbose_name': 'Еженедельный материал', 'verbose_name_plural': 'Еженедельные материалы'},
        ),
        migrations.AlterField(
            model_name='character',
            name='weekly_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.weeklymaterial', verbose_name='Еженедельный материал'),
        ),
        migrations.CreateModel(
            name='UserCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(help_text='Уровень должен быть от 1 до 90', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)])),
                ('is_ascended', models.BooleanField(default=False)),
                ('talent_levels', models.JSONField(default=list)),
                ('target_talent_levels', models.JSONField(default=list)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.character', verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Пользовательский персонаж',
                'verbose_name_plural': 'Пользовательские персонажи',
            },
        ),
    ]
