# Generated by Django 6.0.2 on 2026-02-19 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_alter_weeklymaterial_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usercharacter',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='usercharacter',
            name='is_ascended',
            field=models.BooleanField(default=False, verbose_name='Возвышен'),
        ),
        migrations.AlterField(
            model_name='usercharacter',
            name='talent_levels',
            field=models.JSONField(default=list, verbose_name='Уровни талантов'),
        ),
        migrations.AlterField(
            model_name='usercharacter',
            name='target_talent_levels',
            field=models.JSONField(default=list, verbose_name='Целевые уровни талантов'),
        ),
    ]
