# Generated by Django 6.0.2 on 2026-02-19 13:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_usercharacter_user_alter_usercharacter_is_ascended_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BossMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('boss_name', models.CharField(max_length=200, verbose_name='Название босса')),
            ],
            options={
                'verbose_name': 'Материал босса',
                'verbose_name_plural': 'Материалы босса',
            },
        ),
        migrations.CreateModel(
            name='Mob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Название моба')),
            ],
            options={
                'verbose_name': 'Моб',
                'verbose_name_plural': 'Мобы',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('region', models.CharField(choices=[('MO', 'Мондштадт'), ('LY', 'Ли Юэ'), ('IN', 'Инадзума'), ('SU', 'Сумеру'), ('FO', 'Фонтейн'), ('NA', 'Натлан'), ('NK', 'Нод-Край'), ('SN', 'Снежная')], max_length=2, verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Диковинка',
                'verbose_name_plural': 'Диковинки',
            },
        ),
        migrations.CreateModel(
            name='Stone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('element', models.CharField(choices=[('A', 'Анемо'), ('G', 'Гео'), ('E', 'Электро'), ('D', 'Дендро'), ('H', 'Гидро'), ('P', 'Пиро'), ('C', 'Крио')], max_length=1, verbose_name='Элемент')),
                ('rarity', models.IntegerField(help_text='Редкость камня может быть от 2 до 5 звезд', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)], verbose_name='Редкость')),
            ],
            options={
                'verbose_name': 'Камень',
                'verbose_name_plural': 'Камни',
            },
        ),
        migrations.CreateModel(
            name='TalentMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('region', models.CharField(choices=[('MO', 'Мондштадт'), ('LY', 'Ли Юэ'), ('IN', 'Инадзума'), ('SU', 'Сумеру'), ('FO', 'Фонтейн'), ('NA', 'Натлан'), ('NK', 'Нод-Край'), ('SN', 'Снежная')], max_length=2, verbose_name='Регион')),
                ('rarity', models.IntegerField(help_text='Редкость книги может быть от 2 до 4 звезд', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(4)], verbose_name='Редкость')),
                ('weekday', models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда')], verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'Книга талантов',
                'verbose_name_plural': 'Книги талантов',
            },
        ),
        migrations.AddField(
            model_name='character',
            name='talent_weekday',
            field=models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда')], help_text='День недели, когда фармятся книги талантов', null=True, verbose_name='День недели талантов'),
        ),
        migrations.AlterField(
            model_name='usercharacter',
            name='level',
            field=models.IntegerField(help_text='Уровень должен быть от 1 до 90', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)], verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='character',
            name='boss_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.bossmaterial', verbose_name='Материал босса'),
        ),
        migrations.AddField(
            model_name='character',
            name='mob',
            field=models.ForeignKey(help_text='Выберите моба -> получите все его материалы', null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.mob', verbose_name='Моб (материалы)'),
        ),
        migrations.CreateModel(
            name='MobMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('region', models.CharField(choices=[('MO', 'Мондштадт'), ('LY', 'Ли Юэ'), ('IN', 'Инадзума'), ('SU', 'Сумеру'), ('FO', 'Фонтейн'), ('NA', 'Натлан'), ('NK', 'Нод-Край'), ('SN', 'Снежная')], max_length=2, verbose_name='Регион')),
                ('rarity', models.IntegerField(help_text='Редкость материалов с мобов может быть от 1 до 3 звезд', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Редкость')),
                ('mob_name', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='characters.mob', verbose_name='Название моба')),
            ],
            options={
                'verbose_name': 'Материал моба',
                'verbose_name_plural': 'Материалы мобов',
            },
        ),
        migrations.AddField(
            model_name='character',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.specialty', verbose_name='Диковинка'),
        ),
    ]
