# Generated by Django 6.0.2 on 2026-02-19 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_bossmaterial_mob_specialty_stone_talentmaterial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobmaterial',
            name='region',
        ),
    ]
