# Generated by Django 6.0.2 on 2026-02-24 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_userinventory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinventory',
            options={'verbose_name': 'Пользовательский материал', 'verbose_name_plural': 'Пользовательский инвентарь'},
        ),
        migrations.CreateModel(
            name='PlannedCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_talent_levels', models.JSONField(default=list, verbose_name='Целевые уровни талантов')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.character', verbose_name='Имя')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользовательский персонаж',
                'verbose_name_plural': 'Пользовательские персонажи',
            },
        ),
    ]
